require('nightmare')({show: false})
    .goto('http://192.168.1.1')
    // .type('#index_username', 'admin')
    .type('#password', 'superonline')
    .click('#loginbtn')
    .wait('#setfirstbutton')
    .click('#setfirstbutton')
    .wait(1000)
    .goto('http://192.168.1.1/html/advance.html#device_mngt')
    .wait('#i18n-8')
    .click('#i18n-8')
    .wait(500)
    .click('button#dev_mngt_modal_id_ok')
    .end()
    .then(() => console.log('router restarted'))
    .catch(console.error)
